spring:
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/venus
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: venus-jwt-auth-server
  cloud:
    zookeeper:
      connect-string: localhost:3317
mybatis:
  type-aliases-package: com.kayleh.domain
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.kayleh: debug
rsa:
  key:
    pubKeyFile: D:\project\Venus\venus-jwt-common\src\main\resources\id_key_rsa.pub
    priKeyFile: D:\project\Venus\venus-jwt-common\src\main\resources\id_key_rsa
server:
  port: 9001
