# 文件存储路径; 默认存储在s#  ${catalina.home}/logs/下
LOG_PATH=D:/project/Venus/venus-base/src/main/resources/log
# 单个日志文件的大小 默认是50MB
MAX_FILE_SIZE=5MB
# 文件存储的最大时长,默认为60天
MAX_HISTORY=60
# 日志文件总大小,默认为20GB
TOTAL_SIZE_CAP=20GB
# 日志的监控级别,默认为DEBUG
LOG_LEVEL=DEBUG
